backend:
  name: github
  repo: eng-oscar/omudaala
  branch: main
media_folder: "content/uploads"
public_folder: "/content/uploads"
site_url: "/"
display_url: "/"
collections:
  - name: "listings"
    label: "Rental Listings"
    files:
      - label: "Properties"
        name: "properties"
        file: "content/listings.json"
        format: "json"
        fields:
          - label: "Site"
            name: "site"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "string"
          - label: "Listings"
            name: "listings"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "number"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Type", name: "type", widget: "select", options: ["House","Room","Apartment","Shop"]}
              - {label: "Area", name: "area", widget: "string"}
              - {label: "Monthly Rent", name: "monthly_rent", widget: "string"}
              - {label: "Exact Address Private", name: "exact_address_private", widget: "boolean", default: true}
              - {label: "Owner Phone Private", name: "owner_phone_private", widget: "boolean", default: true}
